name: Bug Report
description: Report a problem with idle-less or Wakeforce
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill in the details below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Reverse Proxy
        - Wakeforce (WoL Gateway)
        - Install Script
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the problem...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: What should have happened instead...

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run install.sh with --wakeforce
        2. Configure domain...
        3. Visit domain...

  - type: input
    id: platform
    attributes:
      label: Platform
      placeholder: "e.g., Raspberry Pi 4 / Ubuntu 22.04 / amd64"

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "e.g., v1.5.2"

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      render: shell
      placeholder: Paste any relevant Docker logs here...
