name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature or improvement...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      placeholder: Why do you need this? What problem does it solve?

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Reverse Proxy
        - Wakeforce (WoL Gateway)
        - Install Script
        - Documentation
        - Other
